apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: stat-relay
    component: carbon
  name: stat-relay
  namespace: stats
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: stat-relay
      component: carbon
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stat-relay
        component: carbon
    spec:
      containers:
      - image: lomik/carbon-clickhouse:v0.10.2
        resources: {}
        imagePullPolicy: IfNotPresent
        name: stat-relay
        ports:
        - containerPort: 2003
          name: plaintext
          protocol: TCP
        - containerPort: 2004
          name: pickle
          protocol: TCP
        volumeMounts:
        - name: stats-conf
          mountPath: /etc/carbon-clickhouse/carbon-clickhouse.conf
          subPath: carbon.relay.conf
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: stats-conf
        configMap:
          name: stats-conf
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stat-api
    component: graphite
  name: stat-api
  namespace: stats
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: stat-api
      component: graphite
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stat-api
        component: graphite
    spec:
      containers:
      - image: lomik/graphite-clickhouse:v0.11.1
        imagePullPolicy: IfNotPresent
        name: stat-api
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 700m
            memory: 6Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: stats-conf
          mountPath: /etc/graphite-clickhouse/graphite-clickhouse.conf
          subPath: graphite.api.conf
        - name: stats-conf
          mountPath: /etc/graphite-clickhouse/rollup.xml
          subPath: rollup.xml
      restartPolicy: Always
      volumes:
      - name: stats-conf
        configMap:
          name: stats-conf
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stat-api
  name: stat-api
  namespace: stats
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: stat-api
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: stat-web
    component: web
  name: stat-web
  namespace: stats
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: stat-web
      component: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stat-web
        component: web
    spec:
      containers:
      - image: gographite/carbonapi:v0.13.0
        imagePullPolicy: IfNotPresent
        name: stat-web
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: stats-conf
          mountPath: /etc/carbonapi.yml
          subPath: carbonapi.yml
      restartPolicy: Always
      volumes:
      - name: stats-conf
        configMap:
          name: stats-conf
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stat-web
  name: stat-web
  namespace: stats
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: stat-web
  sessionAffinity: None
  type: ClusterIP