clickhouse:
  image: yandex/clickhouse-server:19.6.2.11
  volumes:
  - "./rollup.xml:/etc/clickhouse-server/config.d/rollup.xml"
  - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
  - "./data/clickhouse/data:/var/lib/clickhouse/data"
  - "./data/clickhouse/metadata:/var/lib/clickhouse/metadata"
carbon-clickhouse:
  image: lomik/carbon-clickhouse:v0.10.2
  volumes:
  - "./data/carbon-clickhouse:/data/carbon-clickhouse"
  - "./carbon-clickhouse.conf:/etc/carbon-clickhouse/carbon-clickhouse.conf"
  ports:
  - "2003:2003" # plain tcp
  - "2003:2003/udp" # plain udp
  - "2004:2004" # pickle
  - "2006:2006" # prometheus remote write
  links:
  - clickhouse
graphite-clickhouse:
  image: lomik/graphite-clickhouse:v0.11.1
  volumes:
  - "./rollup.xml:/etc/graphite-clickhouse/rollup.xml"
  - "./graphite-clickhouse.conf:/etc/graphite-clickhouse/graphite-clickhouse.conf"
  links:
  - clickhouse
  ports:
  - "9090:9090" # http api access
graphite-web:
  image: graphiteapp/graphite-statsd:1.1.7-3
  volumes:
  - "./graphiteweb_entrypoint.sh:/entrypoint.sh"
  - "./graphiteweb.conf:/opt/graphite/webapp/graphite/local_settings.py"
  entrypoint: /entrypoint.sh
  links:
    - graphite-clickhouse
  ports:
  - "80:80" # http ui
